# fly.toml app configuration file generated for mind-flip on 2023-06-05T21:28:34-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mind-flip"
primary_region = "ord"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
